---
- hosts: all
  connection: local
  roles:
    - common
    - mysql
    - { role: php, run_once: true }
    - apache2
    - { role: memcached, when: install_memcached == true }
    - { role: redis, when: install_redis == true }
    - { role: elasticsearch, when: install_elasticsearch == true }