---

- name: Install apache2
  run_once: true
  apt: name=apache2 state=present
  notify:
    - apache2 restart

- name: Remove unnecessary apache2 files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/var/www/html/"
    - "/etc/apache2/sites-enabled/000-default.conf"
  run_once: true

- name: Enable apache2 mods
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - actions
    - fastcgi
    - rewrite

- name: Create fastcgi configuration
  template: src=etc/apache2/mods-available/fastcgi.conf dest=/etc/apache2/mods-available/fastcgi.conf owner=root group=root mode=0644

- name: Create fastcgi configuration for PHP5.6
  template: src=etc/apache2/mods-available/fastcgi-php56.conf dest=/etc/apache2/mods-available/fastcgi-php56.conf owner=root group=root mode=0644

- name: Enable fastcgi configuration
  file:
    src: "/etc/apache2/mods-available/fastcgi.conf"
    dest: "/etc/apache2/mods-enabled/fastcgi.conf"
    state: link

# - name: Create docroot
#   file:
#     path: "/var/www/{{inventory_hostname}}/{{docroot}}"
#     state: directory
#     owner: www-data
#     group: www-data
#     mode: 0775
#     recurse: yes

- name: Create log directory
  file:
    path: "/var/log/apache2/{{inventory_hostname}}"
    state: directory
    owner: root
    group: adm
    mode: 0750
    recurse: yes

- name: Create apache2 configuration
  template: src=etc/apache2/sites-available/default.conf dest=/etc/apache2/sites-available/{{inventory_hostname}}.conf owner=root group=root mode=0644

- name: Create apache2 SSL configuration
  template: src=etc/apache2/sites-available/ssl.conf dest=/etc/apache2/sites-available/{{inventory_hostname}}-ssl.conf owner=root group=root mode=0644

- name: Enable apache2 configuration
  file:
    src: "/etc/apache2/sites-available/{{inventory_hostname}}.conf"
    dest: "/etc/apache2/sites-enabled/{{inventory_hostname}}.conf"
    state: link
  notify:
    - apache2 restart
