---
# - name: Add repo file
#   template: src=mariadb_ubuntu.list.j2 dest=/etc/apt/sources.list.d/mariadb.list owner=root group=root mode=0644
#   register: mariadb_list

# - name: Add repo key
#   apt_key: id=1BB943DB url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xCBCB082A1BB943DB state=present
#   register: mariadb_key

# - name: Update apt cache
#   apt: update_cache=yes
#   when: mariadb_list.changed == True or mariadb_key.changed == True

# - name: Unattended package installation
#   shell: export DEBIAN_FRONTEND=noninteractive
#   changed_when: false

- name: Install MariaDB
  apt: pkg={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client

- name: Add configuration
  template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
  when: mysql_conf_tpl != 'change_me'
  notify: restart mysql

- name: Start and enable service
  service: name=mysql state=started enabled=yes

- include_tasks: mysql_secure_installation.yml
  when: mysql_secure_installation and mysql_root_password is defined

- include_tasks: create_database.yml