---
- name: Install necessary packages for proper system state
  run_once: true
  apt: name={{ item }} state=latest
  with_items:
    - sysv-rc-conf
    - python-apt
    - python-pycurl
    - python-mysqldb
    - git
    - curl
    - unzip
    - traceroute
    - ack-grep
    - subversion
    - autojump
    - siege

- name: set timezone to Europe/Rome
  timezone:
    name: Europe/Rome

- name: Install Adminer
  when: install_adminer == true
  get_url: url=https://www.adminer.org/latest.php dest=/var/www/{{inventory_hostname}}/{{docroot}}/adminer.php mode=0755
  run_once: true